Avoid issue:  error CS0229: Ambiguity between 'IConnectionStringProperties.ConnectionString' and 'IDbConnection.ConnectionString' Also update to a newer version of EF Core to avoid security issue.